version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./logs:/app/logs
      - uploaded_data:/app/uploads
    environment:
      - DATABASE_URL=postgresql://app_user:app_password@db:5432/tesis_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - tesis-network

  ai_worker:
    build: ./backend
    command: celery -A app.core.celery_app worker --loglevel=info
    volumes:
      - ./backend/app:/app/app
      - ./logs:/app/logs
      - uploaded_data:/app/uploads
      - ./backend/scraper:/app/scraper
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/tesis_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - tesis-network

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - tesis-network

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tesis_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - tesis-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - tesis-network

networks:
  tesis-network:
    driver: bridge

volumes:
  postgres_data:
  uploaded_data:
